FROM httpd:2.4-alpine

# Imagen base de Apache para proyecto-infra
# Servirá contenido estático / PHP (según configuración que definamos en apache/config)
# El DocumentRoot por defecto es /usr/local/apache2/htdocs